<?php

namespace App\Exceptions;

enum ErrorCodes: string
{
    case EES_API_ERROR = 'EES_API_ERROR';
    case EES_CONNECTION_ERROR = 'EES_CONNECTION_ERROR';
    case EES_INVALID_KEY = 'EES_INVALID_KEY';
    case EES_USER_NOT_FOUND = 'EES_USER_NOT_FOUND';
    case EES_USER_NOT_AUTHORIZED = 'EES_USER_NOT_AUTHORIZED';
    case INVALID_LOGIN_CREDENTIALS = 'INVALID_LOGIN_CREDENTIALS';
    case WORKFLOW_INVARIANT_VIOLATION = 'WORKFLOW_INVARIANT_VIOLATION';
}